/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminPricingEntryRouteImport } from './routes/admin.pricing-entry'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPlatformsRouteImport } from './routes/admin.platforms'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminApiPricingEntryRouteImport } from './routes/admin.api-pricing-entry'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingEntryRoute = AdminPricingEntryRouteImport.update({
  id: '/pricing-entry',
  path: '/pricing-entry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformsRoute = AdminPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiPricingEntryRoute = AdminApiPricingEntryRouteImport.update({
  id: '/api-pricing-entry',
  path: '/api-pricing-entry',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/tools': typeof ToolsRoute
  '/admin/api-pricing-entry': typeof AdminApiPricingEntryRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/pricing-entry': typeof AdminPricingEntryRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/tools': typeof ToolsRoute
  '/admin/api-pricing-entry': typeof AdminApiPricingEntryRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/pricing-entry': typeof AdminPricingEntryRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/tools': typeof ToolsRoute
  '/admin/api-pricing-entry': typeof AdminApiPricingEntryRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/platforms': typeof AdminPlatformsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/pricing-entry': typeof AdminPricingEntryRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/tools'
    | '/admin/api-pricing-entry'
    | '/admin/models'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/pricing-entry'
    | '/admin/providers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/tools'
    | '/admin/api-pricing-entry'
    | '/admin/models'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/pricing-entry'
    | '/admin/providers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/tools'
    | '/admin/api-pricing-entry'
    | '/admin/models'
    | '/admin/platforms'
    | '/admin/pricing'
    | '/admin/pricing-entry'
    | '/admin/providers'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-entry': {
      id: '/admin/pricing-entry'
      path: '/pricing-entry'
      fullPath: '/admin/pricing-entry'
      preLoaderRoute: typeof AdminPricingEntryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platforms': {
      id: '/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AdminPlatformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-pricing-entry': {
      id: '/admin/api-pricing-entry'
      path: '/api-pricing-entry'
      fullPath: '/admin/api-pricing-entry'
      preLoaderRoute: typeof AdminApiPricingEntryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApiPricingEntryRoute: typeof AdminApiPricingEntryRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminPlatformsRoute: typeof AdminPlatformsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPricingEntryRoute: typeof AdminPricingEntryRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiPricingEntryRoute: AdminApiPricingEntryRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminPlatformsRoute: AdminPlatformsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPricingEntryRoute: AdminPricingEntryRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
